config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :chatroom_users, only: %i[destroy]
  resources :chatrooms, only: %i[create destroy show index group edit update]
  resources :messages, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :posts
  devise_for :users
  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/users', to: 'users#index'
  get '/group', to: 'chatrooms#group', as: 'group'
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :description, presence: true, length: { maximum: 230 }
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable
  has_many :posts, as: :repostable, dependent: :destroy
  has_many :replys, class_name: 'Comment', as: :commentable, dependent: :destroy

  def count_likes
    likes.count
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    redirect_to root_path
    if @comment.save
    else
      flash[:alert] = 'Something went wrong'
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    commentable = @comment.commentable
    @comment.destroy
    redirect_to root_path
  end

  def comment_params
    params.require(:comment).permit(:commentable_id, :commentable_type, :description)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment.html.erb
<hr>
<div>
  <strong><%= link_to comment.user.username, profile_path(comment.user), style: 'text-decoration: none; color: black; font-size: small' %></strong>
  <br>
  <small>
    <%=comment.description %>
  </small>
  <br>
  <ul class="nav ">
    <li class="nav-item mx-2">
      <% if find_like(comment).nil? %>
        <%= form_for new_like do |form| %>
          <%= form.hidden_field :likeable_id, value: id_pass(comment)%>
          <%= form.hidden_field :likeable_type, value: comment.class %>
          <%= form.submit "Like",  style: 'text-decoration: underline; border: none; background: none; color: black; font-size: small;' %>
          <small><%= comment.count_likes %></small>
        <% end %>
      <% else %>
        <%= link_to "Dislike", like_path(find_like(comment)), method: :delete, style: 'color: black; font-size: small;'%>
        <small><%= comment.count_likes %></small>
      <% end %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to "Repost", new_post_path(repostable_id: comment.id, repostable_type: "Comment"),  style: 'color: black; font-size: small'%>
      <small><%= comment.posts.count %></small>
    </li>
    <% if current_user == comment.user %>
      <li class="nav-item mx-2">
        <%= link_to "Delete", comment_path(comment), method: :delete, style: "color: black; font-size: small;"%>
      </li>
    <% end %>
    <li class="nav-item mx-2">
      <a class="reply">Reply</a>
    </li>
  </ul>
</div>
<div class="reply_area">
  <%= render partial: 'comments/new_comment', locals: {object: comment} %>
  <% if comment.replys.any? %>
    <ul class="reply_list">
      <% comment.replys.each do |reply| %>
        <li>
          <%= render partial: 'comments/comment', locals: {comment: reply} %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/comments/_new_comment.html.erb
<%= form_for Comment.new do |form| %>
  <%= form.hidden_field :commentable_id, value: id_pass(object)%>
  <%= form.hidden_field :commentable_type, value: object.class %>
  <%= form.text_area :description %> <br>
  <%= form.submit "Comment" %>
<% end %>
<br>

app/views/comments/_recomment.html.erb
<div class="container my-3" style="width: 85%;">
<strong><%= link_to comment.user.username, profile_path(comment.user), style: 'text-decoration: none; color: black; font-size: small' %></strong>
<br>
<small>
  <%=comment.description %>
</small>
</div>