config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :chatroom_users, only: %i[destroy]
  resources :chatrooms, only: %i[create destroy show index group edit update]
  resources :messages, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :posts
  devise_for :users
  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/users', to: 'users#index'
  get '/group', to: 'chatrooms#group', as: 'group'
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chatroom.rb
# frozen_string_literal: true

class Chatroom < ApplicationRecord
  validates :room_name, presence: true, if: proc { |c| c.direct == false }
  has_many :messages, dependent: :destroy
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users

  scope :direct, -> { where(direct: true) }

  def last_message
    messages.order(:created_at).last
  end

  def self.find_direct(user, other)
    user.chatrooms.direct.each do |chat|
      return chat if chat.users.include? other
    end

    nil
  end
end

app/controllers/chatrooms_controller.rb
# frozen_string_literal: true

class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: %i[show edit update destroy]

  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.valid?
        if @chatroom.direct
          chatroom = Chatroom.find_direct(current_user, User.find(params[:user_ids].first))
          return redirect_to(chatroom_path(chatroom)) if chatroom.present?
        end

        ChatroomUser.create!(chatroom: @chatroom, user: current_user, admin: true)
        @chatroom.save

        format.html do
          redirect_to chatroom_path(@chatroom)
        end
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { redirect_to :group, alert: 'Need to add group name or select participantes' }
        format.json { render json: @chatroom.errors }
      end
    end
  end

  def group
    @chatroom = Chatroom.new
    @users = User.where.not(id: current_user.id)
  end

  def destroy
    @chatroom.destroy
    redirect_to chatrooms_path
  end

  def index
    @chatrooms = current_user.chatrooms
  end

  def show
    @message = @chatroom.messages.order(:created_at)
  end

  def edit
    if @chatroom.direct
      redirect_to chatroom_path(@chatroom)
      flash[:alert] = "Can't edit direct message"
    end
    @users = @chatroom.users.all.where.not(id: current_user.id)
  end

  def update
    if @chatroom.direct
      redirect_to chatroom_path(@chatroom)
      flash[:alert] = "Can't edit direct message"
    end
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html do
          redirect_to edit_chatroom_path(@chatroom),
                      notice: "Chatroom was successfully updated to #{@chatroom.room_name}."
        end
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit, alert: 'something went wrong' }
        format.json { render json: @chatroom.errors }
      end
    end
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:id])
  end

  def direct_chat(attr)
    return unless attr[:direct]

    other = User.find(attr[:chatroom_users_attributes]['0'][:user_id])
    chatroom = Chatroom.find_direct(current_user, other)

    chatroom_path(chatroom) if chatroom
  end

  def chatroom_params
    if params[:chatroom]
      params.require(:chatroom).permit(:room_name, :direct, user_ids: [])
    else
      params.permit(:room_name, :direct, user_ids: [])
    end
  end
end

app/helpers/chatrooms_helper.rb
# frozen_string_literal: true

module ChatroomsHelper
  def admin(user, chatroom)
    chatroom.chatroom_users.find_by(user_id: user.id).admin
  end
end

app/views/chatrooms/_chatroom_messages.html.erb
<div class="chatroom_content">
  <ul class="message_list">
    <% @chatroom.messages.each do |message| %>
      <div class="d-flex justify-content-<%= message.user==current_user ? "end" : "start"%>">
        <li>
          <%=  render message %>
        </li>
      </div>
    <% end %>
  </ul>
</div>

app/views/chatrooms/edit.html.erb
<h1 class="mb-5"> Chatroom info</h1>
<%= form_with(model: @chatroom) do |f| %>
  <div class="mt-2">
  <%= f.label :room_name %>
  <%= f.text_field :room_name, placeholder: @chatroom.room_name %>
  </div>
  <div class="actions mt-2">
    <%= f.submit 'Change room name', class: "btn btn-outline-primary" %>
  </div>
<% end %>

<h3>Participants list:</h3>
<div id="chatroom_user_list " data-current-chatroom="<%= @chatroom.id %>" class="participant_list">
  <ul>
  <% @users.each do |user|%>
    <li>
      <%=link_to user.username, profile_path(user), class: 'link_to_profile participant' %>
      <% if admin(current_user, @chatroom) %>
        <%= link_to "Remove", chatroom_user_path(chatroom: @chatroom.id, user: user.id), method: :delete, class: 'btn btn-outline-danger' %>
      <% end %>
    </li>
  <% end %>
  </ul>
</div>

<div class="action">
  <%= link_to 'Leave group', chatroom_user_path(chatroom: @chatroom.id, user: current_user.id), method: :delete, class: 'btn btn-outline-danger'%>
</div>

app/views/chatrooms/group.html.erb
<%= form_for @chatroom do |f| %>
  <%= f.text_field :room_name, placeholder: "Enter group name" %>
  <%= f.hidden_field :direct, value: false %>
  <%= f.collection_select :user_ids, @users, :id, :username, {}, { multiple: true, class: "form-select w-50%" } %>
  <%= f.button 'Create', class: 'btn  btn-outline-primary' %>
<% end %>

app/views/chatrooms/index.html.erb
<div class="chatroom_box">
  <%= link_to "DM", users_path, class: "btn btn-outline-primary" %>
  <%= link_to "Group", group_path, class: "btn btn-outline-primary" %>
</div>
<% if @chatrooms.any? %>
  <% @chatrooms.each do |chatroom| %>
    <%= link_to chatroom_path(chatroom), class:"link_to_chatroom" do%>
      <div class="chatroom_box">
        <% if chatroom.direct == false %>
            <%= chatroom.room_name %>
        <% else %>
          <% chatroom.users.each do |user| %>
            <%= user.username unless user==current_user%>
          <% end %>
        <% end %>
        <% if chatroom.messages.any?%>
          <div class="last_message">
            <%= chatroom.last_message.user.username %>:
            <%= chatroom.last_message.content.truncate(27, omission:'...') %><br>
            <%= chatroom.last_message.created_at.strftime('%F %T') %><br>
          </div>
        <% end %>
        <%= link_to "Delete", chatroom_path(chatroom), method: :delete, class: "btn btn-outline-danger" %>
        <hr>
      </div>
    <% end %>

  <% end %>
<% else %>
  <p>Currently no chats</p>
<% end %>

app/views/chatrooms/show.html.erb
<% if @chatroom.direct == false %>
  <h2>
    <%=link_to @chatroom.room_name,edit_chatroom_path(@chatroom), class: "link_to_profile"%>
  </h2>
<% else %>
  <% @chatroom.users.each do |user| %>
    <% unless  user==current_user%>
      <h2>
      <%=link_to user.username,profile_path(user), class: "link_to_profile "%>
      </h2>
    <% end %>
  <% end %>
<% end %>
<div class="chatroom_show">
  <div id="chatroom_data" data-current-user="<%= current_user.id %>" data-current-chatroom="<%= @chatroom.id %>"></div>
  <%= render partial: 'chatrooms/chatroom_messages' %>
  <div class="form-inline">
    <%= form_for Message.new, class: 'form-inline',remote: true do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id%>
      <%= form.hidden_field :chatroom_id, value: @chatroom.id %>
      <%= form.text_area :content, id: 'my_form' %> <br>
      <%= form.submit "Send", class: "btn btn-outline-primary" %>
    <% end %>
  </div>
</div>