config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :chatroom_users, only: %i[destroy]
  resources :chatrooms, only: %i[create destroy show index group edit update]
  resources :messages, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :posts
  devise_for :users
  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/users', to: 'users#index'
  get '/group', to: 'chatrooms#group', as: 'group'
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chatroom.rb
# frozen_string_literal: true

class Chatroom < ApplicationRecord
  validates :room_name, presence: true, if: proc { |c| c.direct == false }
  has_many :messages, dependent: :destroy
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users

  scope :direct, -> { where(direct: true) }

  def last_message
    messages.order(:created_at).last
  end

  def self.find_direct(user, other)
    user.chatrooms.direct.each do |chat|
      return chat if chat.users.include? other
    end

    nil
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  validates :description, length: { maximum: 150 }
  has_one_attached :avatar
  has_many :posts, dependent: :destroy

  has_many :chatroom_users, dependent: :destroy
  has_many :chatrooms, through: :chatroom_users

  has_many :follower_relations, foreign_key: :follower_id, class_name: 'Relation'
  has_many :followees, through: :follower_relations

  has_many :followee_relations, foreign_key: :followee_id, class_name: 'Relation'
  has_many :followers, through: :followee_relations

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  after_commit :add_default_avatar, on: %i[create update]

  def avatar_thumbnail
    avatar.variant(resize: '150x150!').processed
  end

  def chatroom_search
    chatrooms.where(user: current_user)
  end

  private

  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'default_avatar.png'
          )
        ), filename: 'default_avatar.png',
        content_type: 'image/png'
      )
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(:created_at).reverse
  end

  def index
    @users = User.all
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def chatroom_with_user?(user)
    user.chatrooms.each do |chatroom|
      chatroom.chatroom_users.each do |relation|
        return chatroom if relation.user == current_user
      end
    end
    nil
  end
end

app/views/users/index.html.erb
<% @users.each do |user| %>
  <% unless user==current_user %>
    <div class="user_box">
      <%= user.username %>
      <%= link_to 'Message', { :controller => :chatrooms, :action => :create, :user_ids => [user.id], :direct => true } , method: :post, class: 'btn btn-outline-primary'%>
      <%= link_to 'View', profile_path(user), class: "btn btn-outline-primary" %>
      <hr>
    </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div>
  <%= image_tag(@user.avatar, style: "width: 100px; height: 100px;", class: "mr-4") %>
</div>
<div>
  <div>
    <%=@user.username%>
    <br>
    <% if @user.description %>
      <%= @user.description %>
      <br>
    <% end %>
    <%="Followers #{@user.followers.count}" %>
    <%="Following #{@user.followees.count}" %>
  </div>
  <%if @user==current_user%>
    <div class="actions">
      <%= link_to 'Edit', edit_user_registration_path, class:"btn btn-outline-primary" %>
    </div>
  <% else %>
    <div>
      <% if !not_following?(@user) %>
        <%= link_to "Follow", relationships_path(relation: @user), method: :post, class: "btn btn-outline-primary" %>
      <% else %>
        <%= link_to "Unfollow", relationship_path(@user), method: :delete, class: "btn btn-outline-primary" %>
      <% end %>

      <% if @user != current_user %>
        <%=link_to 'Message', { :controller => :chatrooms, :action => :create, :user_ids => [@user.id], :direct => true } , method: :post, class: 'btn btn-outline-primary'%>
      <% end %>
    </div>
  <% end %>
</div>
<% if @posts %>
  <div class="mb-5">
    <% @posts.each do |post| %>
      <%= render 'posts/post_layout', post:post %>
    <% end %>
  </div>
  <br>
<% end %>
<%= javascript_pack_tag 'comment' %>
<%= javascript_pack_tag 'reply' %>