config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :chatroom_users, only: %i[destroy]
  resources :chatrooms, only: %i[create destroy show index group edit update]
  resources :messages, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :posts
  devise_for :users
  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/users', to: 'users#index'
  get '/group', to: 'chatrooms#group', as: 'group'
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :repostable, polymorphic: true, optional: true
  has_one_attached :photo
  has_many :likes, as: :likeable
  has_many :posts, as: :repostable, dependent: :destroy
  has_many :comments, as: :commentable
  validates :content, presence: true, length: { minimum: 2, maximum: 150 }, if: proc { |p| p.repostable.nil? }

  def count_likes
    likes.count
  end

  def show_comments
    comments.all
  end

  def count_comments
    comments.count
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(:created_at).reverse
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/group.html.erb
  def new
    @post = Post.new
    if params[:repostable_id].present? && params[:repostable_type].present?
      @repostable_id = params[:repostable_id]
      @repostable_type = params[:repostable_type]
    else
      @repostable_id = nil
      @repostable_type = nil
    end
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @user = @post.user
    @post.destroy

    respond_to do |format|
      format.html { redirect_to profile_path(@user), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content, :photo, :repostable_id, :repostable_type)
  end

  def require_same_user
    redirect_to posts_url, alert: 'You can edit and delete only your posts' if current_user != @post.user
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if !@repostable_id.nil? && !@repostable_type.nil?%>
    <%= form.hidden_field :repostable_id, value: @repostable_id%>
    <%= form.hidden_field :repostable_type, value: @repostable_type %>
  <% end %>

  <div class="field">
    <%= form.label :content, style: 'display:none;' %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :photo, content_tag(:i, nil, class: "bi bi-image"), class: 'd-flex'  %><br />
    <%= form.file_field :photo, style: 'display:none;' %>
  </div>
  <div class="actions">
    <%= form.submit 'Post', class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/posts/_post_layout.html.erb
<div class="container my-3" style="width: 30%">
  <div class="row">
    <%= link_to post.user.username, profile_path(post.user), class: "card-title col-6", style: 'text-decoration: none; color: black;'%>
    <% if current_user==post.user %>
      <div class="col-6">
        <div class="d-flex justify-content-end">
          <div class="dropdown">
            <button class="btn btn-light btn-sm bi bi-list" style="background: none; box-shadow: none;" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <%= link_to "Edit", edit_post_path(post), class: 'dropdown-item' %>
              <%= link_to "Delete", post_path(post), method: :delete, class: 'dropdown-item', style: 'color: red;' %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <p class="card-text"><%= post.content %></p>
  <% if !post.repostable_id.nil? %>
    <%if post.repostable_type=="Post" %>
      <%= render partial: "posts/repost", locals: {post: Post.find(post.repostable_id)} %>
    <% else %>
      <%= render partial: "comments/recomment", locals: {comment: Comment.find(post.repostable_id)}%>
    <% end %>
  <% end %>
  <% if post.photo.attached? %>
    <%= image_tag(post.photo, style: "width: 100%")%>
  <% end %>
    <ul class="nav justify-content-center mt-3">
      <li class="nav-item mx-2">
        <% if find_like(post).nil? %>
          <%= form_for new_like do |form| %>
            <%= form.hidden_field :likeable_id, value: id_pass(post)%>
            <%= form.hidden_field :likeable_type, value: post.class %>
            <%= button_tag content_tag(:i, nil, class: "bi bi-heart"), type: 'submit', class: "btn btn-outline-danger btn-sm" %>
            <%= post.count_likes %>
          <% end %>
        <% else %>
          <%= link_to content_tag(:i, nil, class: "bi bi-heart"), like_path(find_like(post)), method: :delete, class: "btn btn-danger btn-sm"%>
          <%= post.count_likes %>
        <% end %>
      </li>
      <li class="nav-item mx-2">
        <a class="comment"><i class="bi bi-chat-square-dots btn btn-outline-success btn-sm"></i></a>
        <%= post.count_comments %>
      </li>
      <li class="nav-item mx-2">
        <%= link_to content_tag(:i, nil, class: "bi bi-arrow-90deg-right"), new_post_path(repostable_id: post.id, repostable_type: "Post"), class: "btn btn-outline-primary btn-sm"%>
        <%= post.posts.count %>
      </li>
    </ul>
  <div class="comment_area">
    <br>
    <%= render partial: 'comments/new_comment', locals: {object: post} %>
    <% if post.comments.any? %>
      <strong>Comments:</strong>
      <%= render post.comments %>
    <% end %>
  </div>
  <hr>
</div>

app/views/posts/_repost.html.erb
<div class="container my-3" style="width: 85%;">
  <div class="row">
    <%= link_to post.user.username, profile_path(post.user), class: "card-title col-6", style: 'text-decoration: none; color: black;'%>
  </div>
  <p class="card-text"><%= post.content %></p>
  <% if !post.repostable_id.nil? %>
    <% if post.repostable_type == 'Post'%>
      <%= render partial: 'posts/repost', locals: {post: Post.find(post.repostable_id)} %>
    <%else %>
      <%= render partial: 'comments/recomment', locals: {comment: Comment.find(post.repostable_id)} %>
    <% end %>
  <% end %>
  <% if post.photo.attached? %>
    <%= image_tag(post.photo, style: "width: 100%")%>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<div class=" container justify-content-center">
  <% @posts.each do |post| %>
      <%= render 'post_layout', post: post %>
  <% end %>
</div>

<%= javascript_pack_tag 'comment' %>
<%= javascript_pack_tag 'reply' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render 'post_layout', post: @post %>

<%= javascript_pack_tag  'comment'%>
<%= javascript_pack_tag  'reply'%>